version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
  db:
    build:
        context: .  
        dockerfile: Dockerfile.db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD