#!/bin/bash

# Создание базы данных
sudo -u postgres psql postgres
CREATE DATABASE lt1;
\q

# Создание таблицы
sudo -u postgres psql lt1
\c lt1
CREATE TABLE log_entries (
 id SERIAL PRIMARY KEY,
 tmstmp TIMESTAMP NOT NULL,
 srcip inet NOT NULL,
 len varchar(255) NOT NULL,
 ttl varchar(255),
 innerid varchar(255),
 spt varchar(255),
 dpt varchar(255),
 wndw varchar(255)
);
\q

# Создание пользователя и назначение прав
sudo -u postgres psql
CREATE ROLE raf WITH LOGIN PASSWORD 'qwq121';
GRANT ALL PRIVILEGES ON DATABASE lt1 TO raf;
GRANT ALL PRIVILEGES ON TABLE log_entries TO raf;
GRANT ALL PRIVILEGES ON SEQUENCE log_entries_id_seq TO raf;
\q
# Обратите внимание, что для выполнения команд, требующих привилегии суперпользователя, используется команда sudo с указанием пользователя postgres.
