#!/bin/bash

# Creating a 'logtracker' database
echo "CREATE DATABASE logtracker;" | psql

# Creating a user with the password
echo "CREATE ROLE raf WITH LOGIN PASSWORD '******';" | psql -U postgres

# Give the raf user the rights to the 'logtracker' database
echo "GRANT ALL PRIVILEGES ON DATABASE logtracker TO raf;" | psql -U postgres

# Creating the log_entries table in the logtracker database
echo "CREATE TABLE log_entries (
 id SERIAL PRIMARY KEY,
 tmstmp TIMESTAMP NOT NULL,
 srcip inet NOT NULL,
 len varchar(255) NOT NULL,
 ttl varchar(255),
 innerid varchar(255),
 spt varchar(255),
 dpt varchar(255),
 wndw varchar(255)
);" | psql -d logtracker -U raf

# Give the raf user rights to the log_entries table
echo "GRANT ALL PRIVILEGES ON TABLE log_entries TO raf;" | psql -d logtracker -U raf

# We give the raf user the rights to the log_entries_id_seq sequence
echo "GRANT ALL PRIVILEGES ON SEQUENCE log_entries_id_seq TO raf;" | psql -d logtracker -U raf

# make the file executable:
# chmod +x filename
#
# make the file non-executable:
# chmod -x filename
