#!/bin/bash

# Подключение к PostgreSQL
sudo -u postgres psql -c "CREATE DATABASE ltr;"

# Создание таблицы в базе данных ltr
sudo -u postgres psql -d ltr -c "CREATE TABLE lg_tr (
 serial_number SERIAL PRIMARY KEY,
 first_name VARCHAR(100),
 last_name VARCHAR(100)
);"

# ---------------------------------
#!/bin/bash

# Подключаемся к PostgreSQL как пользователь postgres
psql -U postgres -c "CREATE DATABASE ltr;"

# Подключаемся к новой базе данных
psql -d ltr -c "CREATE TABLE lg_tr (serial_number INT PRIMARY KEY, first_name VARCHAR(255), last_name VARCHAR(255));"
